[package]
name = "bitop"
version = "1.0.1"
authors = ["oni@cynetlab.com <oni@cynetlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
